# API Mock Server Configuration
# Define your endpoints and their corresponding response files here

endpoints:
  # Example 1: Simple GET endpoint
  /api/v1/users:
    methods: ['GET']
    description: "Get list of users"
    response_file: "users_list.json"
    status_code: 200
  
  # Example 2: Single resource endpoint
  /api/v1/users/123:
    methods: ['GET']
    description: "Get user by ID"
    response_file: "user_detail.json"
    status_code: 200
  
  # Example 3: Multiple methods with different responses
  /api/v1/products:
    methods: ['GET', 'POST']
    description: "Products endpoint supporting GET and POST"
    responses:
      GET: "products_list.json"
      POST: "product_created.json"
    status_code: 200
  
  # Example 4: Error response simulation
  /api/v1/error:
    methods: ['GET']
    description: "Simulate error response"
    response_file: "error_response.json"
    status_code: 400
  
  # Example 5: Endpoint with simulated delay (in seconds)
  /api/v1/slow:
    methods: ['GET']
    description: "Simulate slow response"
    response_file: "slow_response.json"
    status_code: 200
    delay: 2

# =============================================================================
# FREE LINK API - RAFL (Rakuten Affiliate Free Link API)
# =============================================================================
  
  # SUCCESS SCENARIOS
  # -----------------
  
  # Success: Item URL without pb_id
  /freelink/v1/success/item:
    methods: ['POST']
    description: "Free Link API - Success response for item URL"
    response_file: "freelink_success_item.json"
    status_code: 200
  
  # Success: Item URL with pb_id
  /freelink/v1/success/item-with-pbid:
    methods: ['POST']
    description: "Free Link API - Success response for item URL with pb_id"
    response_file: "freelink_success_item_with_pbid.json"
    status_code: 200
  
  # Success: Shop URL
  /freelink/v1/success/shop:
    methods: ['POST']
    description: "Free Link API - Success response for shop URL"
    response_file: "freelink_success_shop.json"
    status_code: 200
  
  # Success: Deeplink (210 prefix shop)
  /freelink/v1/success/deeplink:
    methods: ['POST']
    description: "Free Link API - Success response with deeplink for 210 prefix shop"
    response_file: "freelink_success_deeplink.json"
    status_code: 200
  
  # ERROR SCENARIOS - Validation Errors
  # ------------------------------------
  
  # Error: Key missing
  /freelink/v1/error/key-missing:
    methods: ['POST']
    description: "Free Link API - Error: key parameter missing"
    response_file: "freelink_error_key_missing.json"
    status_code: 400
  
  # Error: Key invalid (authentication failed)
  /freelink/v1/error/key-invalid:
    methods: ['POST']
    description: "Free Link API - Error: key authentication error"
    response_file: "freelink_error_key_invalid.json"
    status_code: 400
  
  # Error: affiliate_id missing
  /freelink/v1/error/affiliate-id-missing:
    methods: ['POST']
    description: "Free Link API - Error: affiliate_id parameter missing"
    response_file: "freelink_error_affiliate_id_missing.json"
    status_code: 400
  
  # Error: affiliate_id format error
  /freelink/v1/error/affiliate-id-format:
    methods: ['POST']
    description: "Free Link API - Error: affiliate_id format is invalid"
    response_file: "freelink_error_affiliate_id_format.json"
    status_code: 400
  
  # Error: affiliate_id discrepancy
  /freelink/v1/error/affiliate-id-discrepancy:
    methods: ['POST']
    description: "Free Link API - Error: affiliate_id discrepancy with af_id"
    response_file: "freelink_error_affiliate_id_discrepancy.json"
    status_code: 400
  
  # Error: af_id missing
  /freelink/v1/error/afid-missing:
    methods: ['POST']
    description: "Free Link API - Error: af_id parameter missing"
    response_file: "freelink_error_afid_missing.json"
    status_code: 400
  
  # Error: af_id does not exist
  /freelink/v1/error/afid-not-exist:
    methods: ['POST']
    description: "Free Link API - Error: af_id does not exist in database"
    response_file: "freelink_error_afid_not_exist.json"
    status_code: 400
  
  # Error: af_id status not ok
  /freelink/v1/error/afid-status:
    methods: ['POST']
    description: "Free Link API - Error: af_id status is not ok"
    response_file: "freelink_error_afid_status.json"
    status_code: 400
  
  # Error: af_id blacklisted
  /freelink/v1/error/afid-blacklisted:
    methods: ['POST']
    description: "Free Link API - Error: af_id is blacklisted"
    response_file: "freelink_error_afid_blacklisted.json"
    status_code: 400
  
  # Error: URL missing
  /freelink/v1/error/url-missing:
    methods: ['POST']
    description: "Free Link API - Error: url parameter missing"
    response_file: "freelink_error_url_missing.json"
    status_code: 400
  
  # Error: URL format error
  /freelink/v1/error/url-format:
    methods: ['POST']
    description: "Free Link API - Error: url format is invalid"
    response_file: "freelink_error_url_format.json"
    status_code: 400
  
  # Error: URL denied (blocked URL)
  /freelink/v1/error/url-denied:
    methods: ['POST']
    description: "Free Link API - Error: url is in denied list"
    response_file: "freelink_error_url_denied.json"
    status_code: 400
  
  # Error: pb_id format error
  /freelink/v1/error/pbid-format:
    methods: ['POST']
    description: "Free Link API - Error: pb_id format is invalid"
    response_file: "freelink_error_pbid_format.json"
    status_code: 400
  
  # Error: shop_id does not exist
  /freelink/v1/error/shop-not-exist:
    methods: ['POST']
    description: "Free Link API - Error: shop_id does not exist"
    response_file: "freelink_error_shop_not_exist.json"
    status_code: 400
  
  # Error: System error (500)
  /freelink/v1/error/system:
    methods: ['POST']
    description: "Free Link API - Error: Internal system error"
    response_file: "freelink_error_system.json"
    status_code: 500

# Add your own custom endpoints below:
# /your/endpoint/path:
#   methods: ['GET', 'POST', ...]
#   description: "Your endpoint description"
#   response_file: "your_response.json"
#   status_code: 200

